export enum TABLE_CONFIG {
  ITEMS_PER_PAGE_SM = 10,
  ITEMS_PER_LINE_SM = 2,
  ITEMS_PER_PAGE_MD = 20,
  ITEMS_PER_LINE_MD = 6,
  ITEMS_PER_PAGE_LG = 30,
  ITEMS_PER_LINE_LG = 8,
  ITEMS_PER_PAGE_XL = 14,
  ITEMS_PER_LINE_XL = 35,
  ITEMS_PER_PAGE_XXL = 40,
  ITEMS_PER_LINE_XXL = 12,
}
