export enum TABLE_CONFIG {
  ITEMS_PER_PAGE_SM = 20,
  ITEMS_PER_LINE_SM = 2,
  ITEMS_PER_PAGE_MD = 27,
  ITEMS_PER_LINE_MD = 6,
  ITEMS_PER_PAGE_LG = 36,
  ITEMS_PER_LINE_LG = 8,
  ITEMS_PER_PAGE_XL = 42,
  ITEMS_PER_LINE_XL = 14,
  ITEMS_PER_PAGE_XXL = 48,
  ITEMS_PER_LINE_XXL = 12,
}
